### ISSUE TITLE
Ability to wait for indexing to finish before running static builds

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2825]
## Summary

As a Tina dev using Cloud API & static builds I want my builds to wait for indexing to finish before my site is built so that my static builds don't use outdated/invalid data.

### Expected Results

When building content statically,
- Site build doesn't start until indexing is finished.
      - Suggestion 1): The site build is wrapped in something that waits on proper indexing status (e.g "tinacms server:start -c \"next build\"")
       - Suggestion 2): Github action build-step that waits on proper indexing status

### Notes

As is, for static builds that use the data layer, there is a race condition (since the indexing would start at the same time as the build). For larger sites, or any time the schema is modified, this is increasingly likely to be an issue.

Related to: https://github.com/tinacms/tinacms/issues/2791#issuecomment-1103967563

Write-up: https://docs.google.com/document/d/1EUBY6PzDF49_F_NORuYoEuanq2phUpggKr2OJvMFm44/edit?usp=sharing

Tickets:

- [x] https://github.com/tinacms/product-roadmap/issues/153
- [x] https://github.com/tinacms/product-roadmap/issues/154
- [x] https://github.com/tinacms/product-roadmap/issues/155
- [x] https://github.com/tinacms/product-roadmap/issues/156
- [x] https://github.com/tinacms/tinacms/issues/2777
- [x] https://github.com/tinacms/tina-cloud/issues/1551
