### ISSUE TITLE
🧪 Form - Add Test 

### ISSUE THREAD

**Issue by JackDevAU** [tinacms/tinacms#4542]
CC: @ncn-ssw @Ben0189 @jeffsee55 @scottgallant @wicksipedia 

Hi Team, 

There aren't any tests for local storage, which requires integration tests on a core part of tinacms. 

### Tasks, 

- [x] Implement Playwright and add it to CI 
- [x] Implement one UI test, make sure it works in CI 
- [x] Add basic tests for local storage

**Comment by Ben0189** [comment]
Progress update 🚀

- Done - Set up a specific TinaCMS example project for Playwright
- Done - Completed the initial setup and configuration for Playwright.
- Done - Executed the first end-to-end (E2E) test to create a blog post.

Moving on we can start write some E2E test for local storage retain edit🙌.

**Comment by Ben0189** [comment]
As per conversation with @JackDevAU and @wicksipedia in daily meeting, the test for the local storage retain edit feature can be marked as skipped in the CI pipeline for now since the local storage feature is not yet implemented😊,

**Comment by Ben0189** [comment]
Progress update 🚀

Done - Added UI test for local storage edit retain on input and rich text editor 
Done - Added playwright test workflow in CI GitHub action 
In progress - Improve test to use playwright best practices
In progress - Improve CI workflow for playwright test

re-estimated to 4

**Comment by Ben0189** [comment]
Progress update 🚀
Done - Playwright setup finished with one working test (create blog post and two draft test for local storage retain edit)
Done - CI workflow setup for playwright test to run (e2e test workflow)

BLOCKED - pr cannot be build due to broken pipeline 
https://github.com/orgs/tinacms/projects/38/views/1?pane=issue&itemId=68475801

**Comment by Ben0189** [comment]
✅ Done - PR merged https://github.com/tinacms/tinacms/pull/4592
