### ISSUE TITLE
📝 TinaCMS - Onboarding Document

### ISSUE THREAD

**Issue by ncn-ssw** [tinacms/tinacms#4547]
CC: @Ben0189 @scottgallant 

Hey Team, 

There isn't a lot of docs giving any information on the many packages that TinaCMS looks after. This document aims to give a high level overview of each of these as well as other development processes, eg. how deployment works. 

### Tasks
- [ ] Start documenting in detail all packages and make notes of what is what 
- [ ] Draw a dependency graph
- [ ] Get documents test passed
- [ ] Update https://tina.io/docs/contributing/guidelines/

**Comment by JackDevAU** [comment]
Update:

Some more documentation has been updated (locally). Also re-did the Getting Started with Next.js to flow better (draft).

**Comment by kulesy** [comment]
Closing as stale — this internal onboarding document task has been open since May 2024 and is no longer actionable. Part of backlog refinement.
