### ISSUE TITLE
📝 Docs - Approach to using Tina with the Next.js App Router

### ISSUE THREAD

**Issue by ncn-ssw** [tinacms/tinacms#4548]
Documentation update.

## Tasks

- [x] Update starter templates that use Next to use App Router
- [x] Add page to docs site on how to use Tina + AppRouter

**Comment by bradystroud** [comment]
@amankumarrr got this working on https://ssw.com.au
He might be able to assist here

**Comment by JackDevAU** [comment]
Update:

Draft getting started documentation has been written. 
Still need to replace existing docs once test passed

**Comment by JackDevAU** [comment]
Update: 

Initial work to update all packages to latest for the https://github.com/tinacms/tina-cloud-starter. 
PR: https://github.com/tinacms/tina-cloud-starter/pull/510


- [ ] Update [<tina-cloud-starter>](https://github.com/tinacms/tina-cloud-starter) to App Router
- [ ] Update packages for https://github.com/tinacms/tina-cloud-starter
- [ ] Update https://github.com/tinacms/tina-cloud-starter to use App Router

**Comment by JackDevAU** [comment]
Update:

The Tina Cloud Starter has now been upgraded to use the App Router instead of the Pages Router. 
The other starter is in the process of being upgraded. Currently updating packages and migrating to Nextjs 14. https://github.com/tinacms/tina-barebones-starter/pull/241

The Docs are still underway

**Comment by Ben0189** [comment]
Update 

PR is merged barebone stater is now using app router - https://github.com/tinacms/tina-barebones-starter/pull/242

**Comment by JackDevAU** [comment]
Update: 

Barebones Starter & Tina Cloud Starter have both been updated to use the App Router. Prior to the migration we also updated the packages to the latest and improved the Pages Router.  

Unfortunately the docs are still a WIP

**Comment by JackDevAU** [comment]
Update:

Docs PR in Review: https://github.com/tinacms/tina.io/pull/1915

**Comment by JackDevAU** [comment]
✅ Done - Docs have been updated and are now live at https://tina.io/docs/frameworks/next/overview/
