### ISSUE TITLE
🚸 TinaCMS POC - Bulk load media content for infinite scroll and searching

### ISSUE THREAD

**Issue by ncn-ssw** [tinacms/tinacms#4568]
In relation to #2053

> There is no way to search for media files within the editor. You have to slowly paginate through each page looking for the desired asset. The solution is to implement a search bar and infinite scrolling within the media manager.

The recommended solution would be to have the server paginate in large pages. Most repositories should be able to have their data grabbed within a single page while larger requests can still be paginated if required. The server will then send back a single response object to the client. The client will store this in memory where it can be used by both the infinite scroll and search bar.

The existing `list()` function in TinaCMS has a limit option which should allow changing the number of items returned per page. It's recommended that a POC is first developed using this as it may not be necessary to create any new endpoints in TinaCloud. 

## Tasks
- [x] Investigate into seeing if we can get information on the amount of media being pulled by clients.
- [x] Use the `list()` function to try retrieve all images in memory. Setting a large enough page size should allow most images in most user's repos to be pulled down.
- [x] If this doesn't work, draft up PBIs for implementing back-end endpoints to achieve this.

**Comment by kldavis4** [comment]
internal demo https://youtu.be/op_C3Anl63I
branch https://github.com/tinacms/tinacms/pull/4599

follow-ups:
- demo is on local fs - need to test w/ other media manager implementations

**Comment by ncn-ssw** [comment]
CC @kldavis4 @wicksipedia 

I have pulled and run #4599 locally. It successfully paginates correctly when given a folder of 922 images.

Points that we will need to address when moving beyond the POC:

- As mentioned in the demo video, the UI will need additional polish such as:
    - The icon in the search button being centered
    - The search/action bar not splitting in 2 when shrunk
- When there are no search results, the text displayed is "Drag and drop assets here" rather than "No results found"
- We need to consider whether uploading should be allowed when search results are displayed. If a user uploads an item that does not match the criteria, does that mean it should not be displayed? But would that behavior lead to confusion?
- The matching is on sub-tokens surprised me - for instance, filename "screenshot-202.png" will match "screenshot" and "202" but "screen" does not.

**Comment by kldavis4** [comment]
Did you try it locally or with Tina cloud?

**Comment by ncn-ssw** [comment]
Locally.

**Comment by ncn-ssw** [comment]
Work remaining:
- [ ] Investigate into seeing if we can get information on the amount of media being pulled by clients.
- [ ] Create Spike PBI to complete the initial design of the bulk load for infinite scroll and searching

**Comment by kldavis4** [comment]
Ok, this took longer than expected due to typescript issues with the search library. Also, made a couple tweaks to attempt to improve the speed, including caching the client side auth check and increasing the page size to 100.

I copied the media from the SSW website to this starter repo: https://github.com/kldavis4/tina-cloud-starter-20240301 and added the tag version with media search.

In my testing, it took about 97 seconds to load the entire set of images. Each request took around 600ms and most (maybe all) directories were able to load in a single request. So that would be around ~160 directories.

My thoughts are that this is pretty slow :) I think the number of directories is quite high with SSW, though, so might not be too terrible for the average site. I think we should look into improving the performance of the directory listing endpoint. Maybe keep a server side file listing in a db or s3 object that gets synced whenever there are changes to media. Also, on the client side, when we find multiple subdirectories in a folder, we can fetch those in parallel (currently everything is sequential). Also, a more complex sync solution where we don't sync every time the media manager is opened might be worth looking into.

It looks like cloudinary is even slower, > 1s per request, so we'll have to consider that as well.

**Comment by kldavis4** [comment]
Initial results of analysis in this spreadsheet: https://docs.google.com/spreadsheets/d/1PLUwzpR1CNzLYO4hPMOfNDoogRpei_yp4P9NEOM0vsQ/edit?gid=546466586#gid=546466586

raw data from S3 [allitems.txt.zip](https://github.com/user-attachments/files/16186498/allitems.txt.zip)

Script for pulling the raw data
```
#!/bin/bash

AWS_PROFILE=141216917243_AdministratorAccess
BUCKET_NAME="assets.tina.io"
FOLDER_PATH="originals/"
MAX_ITEMS=100

# Function to list objects starting from a given continuation token
function list_objects {
    local token=$1
    if [ -z "$token" ]; then
        AWS_PROFILE=$AWS_PROFILE aws s3api list-objects-v2 --bucket "$BUCKET_NAME" --prefix "$FOLDER_PATH" --max-items $MAX_ITEMS
    else
        AWS_PROFILE=$AWS_PROFILE aws s3api list-objects-v2 --bucket "$BUCKET_NAME" --prefix "$FOLDER_PATH" --starting-token "$token" --max-items $MAX_ITEMS
    fi
}

# Initial call to list objects
result=$(list_objects)

# Loop to handle pagination
while true; do
    # Print object keys
    echo "$result" | jq -r '.Contents[].Key'

    # Check if there is a NextContinuationToken for pagination
    token=$(echo "$result" | jq -r '.NextToken')
    if [ "$token" == "null" ]; then
        break
    fi

    # Get the next set of results
    result=$(list_objects "$token")
done
```

Script for performing analysis
```
const fs = require('fs');

const allItems = fs.readFileSync('allitems.txt', 'utf8').split('\n');

const projects = {};
for (let i = 0; i < allItems.length; i++) {
    const parts = allItems[i].split('/');
    const projectId = parts[1];
    
    const fileName = parts[parts.length - 1];
    const fileParts = fileName.split('.');
    const suffix = fileParts[fileParts.length - 1].toLowerCase();
    // const isOther = suffix === 'html' || suffix === 'js' || suffix === 'htaccess' || suffix === 'ds_store' || suffix === 'gitignore' || suffix === 'md' || suffix.startsWith('html') || suffix === 'tmp' || suffix === 'json' || suffix === 'keep' || suffix === 'webmanifest' || suffix === 'txt' || suffix === 'yml' || suffix === 'gitkeep' || suffix === 'filepart' || suffix === 'centers' || suffix === 'big' || suffix === 'xml' || suffix === 'css' || suffix === 'scss' || suffix === 'ts' || suffix === 'php' || suffix === 'xsl' || suffix === 'yaml' || suffix === 'yaml' || suffix === 'bak' || suffix === 'identifier' || suffix === 'less' || suffix === 'jsonl' || suffix === 'markdown' || suffix === 'htm' || suffix === 'mdx' || suffix === 'map' || suffix === 'log' || suffix === 'gql' || suffix === 'icloud' || suffix === 'dockerfile' || suffix === 'npmrc' || suffix === 'ipynb' || suffix === 'rpm' || suffix === 'db' || suffix === 'properties' || suffix === 'njk' || suffix === 'erb' || suffix === 'crdownload' || suffix === 'wasm' || suffix === 'tsx' || suffix === 'toml' || suffix === 'time' || suffix == 'text' || suffix === 'sh' || suffix === 'scssc'  || suffix === 'sass'  || suffix === 'rst' || suffix === 'rb' || suffix === 's' || suffix === 'options'
    const isImage = suffix === 'jpg' || suffix === 'png' || suffix === 'jpeg' || suffix === 'gif' || suffix === 'svg' || suffix === 'webp' || suffix === 'avif' || suffix === 'pdf' || suffix === 'mp4' || suffix === 'wav' || suffix === 'tiff' || suffix === 'woff' || suffix === 'woff2' || suffix === 'ico' || suffix === 'psd' || suffix === 'ttf' || suffix === 'otf' || suffix === 'zip' || suffix === 'mov' || suffix === 'docx' || suffix === 'xlsx' || suffix === 'doc' || suffix === 'mp3' || suffix === 'webm' || suffix === 'webm' || suffix === 'eot' || suffix === 'vtt' || suffix === 'heic' || suffix === 'jfif' || suffix === 'aseprite' || suffix === 'pptx' || suffix === 'eps' || suffix === 'ai' || suffix === 'bmp' || suffix === 'tif' || suffix === 'svgz' || suffix === 'swf' || suffix === 'fla' || suffix === 'xcf' || suffix === 'lottie' || suffix === 'epub' || suffix === 'kra' || suffix === 'gpx' || suffix === 'dia' || suffix === 'bcmap' || suffix === 'glb' || suffix === 'xls' || suffix === 'rtf' || suffix === 'csv' || suffix === 'gz' || suffix === 'riv' || suffix === 'm4a' || suffix === 'm4v'
    if (!isImage) {
        continue
    }

    if (!projects[projectId]) {
        projects[projectId] = {};
    }
    const project = projects[projectId];
    project['filecount'] = (project['filecount'] || 0) + 1;

    let tree = project['tree'] || {};
    project['tree'] = tree;

    let ptr = project['tree'];
    for (let j = 2; j < parts.length - 1; j++) {
        const part = parts[j];
        ptr[part] = ptr[part] || {};
        ptr = ptr[part];
    }
}

const calculateTreeDepth = (tree) => {
    let maxDepth = 0;
    for (const key in tree) {
        const depth = calculateTreeDepth(tree[key]);
        if (depth > maxDepth) {
            maxDepth = depth;
        }
    }
    return maxDepth + 1;
}

const calculateMaxTreeWidth = (tree) => {
    let maxWidth = 1;
    for (const key in tree) {
        const width = calculateMaxTreeWidth(tree[key]);
        if (width > maxWidth) {
            maxWidth = width;
        }
    }
    return Object.keys(tree).length > maxWidth ? Object.keys(tree).length : maxWidth;
}

const calculateNumberTreeNodes = (tree) => {
    let count = 0;
    for (const key in tree) {
        count += calculateNumberTreeNodes(tree[key]);
    }
    return count + 1;
}

for (const projectId in projects) {
    const project = projects[projectId];
    project['depth'] = calculateTreeDepth(project['tree']);
    project['width'] = calculateMaxTreeWidth(project['tree']);
    project['nodes'] = calculateNumberTreeNodes(project['tree']);
}


console.log('projectId,filecount,depth,width,nodes');
for (const projectId in projects) {
    const project = projects[projectId];
    console.log(`${projectId},${project['filecount']},${project['depth']},${project['width']},${project['nodes']}`);
}
```

CSV output [analysis.csv](https://github.com/user-attachments/files/16186515/analysis.csv)

**Comment by ncn-ssw** [comment]
@kldavis4 @brookjeynes-ssw @wicksipedia 

✅ Done - PBIs drafted/amended

As per meeting today with Kelly and Brook, the following PBIs were drafted or amended based on the findings of the POC. I have listed them in the order we believe the work should be conducted.

1. https://github.com/tinacms/tina-cloud/issues/2073 - This issue with indexing should be resolved first. Comment added noting that the [best solution](https://github.com/tinacms/tina-cloud/issues/2073#issuecomment-2237833229) is to use `git sparse-checkout` and why.
2. https://github.com/tinacms/tina-cloud/issues/2035 - A comment has been added recommending that infinite scrolling is implemented separately to search, as additional work will be required to implement search properly.
3. https://github.com/tinacms/tina-cloud/issues/2103 - Retrieving media when there are many directories is slow. We therefore believe that an index of the media needs to be created that can be queried as a collection. This work should also permit handling multiple branches.
4. https://github.com/tinacms/tina-cloud/issues/2104 - Design how the Media Manager should be updated to use the updated query mechanism
5. https://github.com/tinacms/tina-cloud/issues/2106 - Design how developers using non-Tina Cloud media management can update their index
