### ISSUE TITLE
📦 TinaCMS - Package Updates for Slate and Plate

### ISSUE THREAD

**Issue by ncn-ssw** [tinacms/tinacms#4619]
CC @adamcogan @wicksipedia 

Hey Team,

### Description: 

There are currently a lot of packages, over quite a few projects. Lets see if we can update them! 
Let's also look into seeing if we can update Plate to the latest.

### Tasks

- [x] Slate - Identify the current version we are using
- [x] Slate - Check and document the latest version available
- [x] Slate - List any new features in the latest version
- [x] Plate - Identify the current version we are using
- [x] Plate - Check and document the latest version available
- [x] Plate - List any new features in the latest version
- [x] Update Plate

**Comment by JackDevAU** [comment]
> Slate - Identify the current version we are using

We are currently on version: **0.94.1**

`"slate": "^0.94.1",`
`"slate-history": "^0.93.0",`
`"slate-hyperscript": "^0.77.0",`
`"slate-react": ^0.97.1",`

> Slate - Check and document the latest version available
> Slate - List any new features in the latest version

Latest version: [0.103.0](https://www.npmjs.com/package/slate/v/0.103.0)

Nothing of much note - Just some bug fixes, code cleanup and code tidy. 

We are basically up to date with Slate!

> Plate - Identify the current version we are using

We are currently on version: **21.4.0**

"@udecode/plate-headless": "^21.4.0",

> Plate - Check and document the latest version available

Latest version is [21.5.0](https://www.npmjs.com/package/@udecode/plate-headless)
However the latest Plate version is [36.0.6](https://www.npmjs.com/package/@udecode/plate-core)

> Plate - List any new features in the latest version

The docs around the version "headless" slate seem to be non-existant... Looking to switch to Plate instead.


⏳ Updating package is in progress but awaiting the React 18 upgrade!

**Comment by JackDevAU** [comment]
Update: 

The Plate upgrade is going well. It's currently looking like quite a big change.
Currently need https://github.com/tinacms/tinacms/pull/4660 to be merged before I can progress further. 

Current progress can be found on a branch called: [plate-v2](https://github.com/tinacms/tinacms/tree/plate-v2)

**Comment by JackDevAU** [comment]
Update: 

A few road blockers currently working through. `react-dnd` seems to have moved to full `esm` which is causing us some issues. Styling is also a constant blocker. Due to how we render the sidebar a lot of items need a very high z index 

![Image](https://github.com/user-attachments/assets/b214303c-145b-420c-b982-1046cfa4a1a0)
**Figure: Preview of latest Slate editor**

**Comment by JackDevAU** [comment]
Updates:

Due to the issues surrounding `react-dnd` and our `esm` issues we won't be adding drag and drop support _yet_. 
Apart from that hiccup, the Plate upgrade is progressing well, see the before and after below. This will also come with a `/` Slash Command and floating menu (highlight or click on a word will bring this menu up). For this PBI, we won't be adding any more specific plugins or elements than those we had previously as extras will be covered in separate PBIs. 


Before:

![Image](https://github.com/user-attachments/assets/88166ba1-f9b1-42d6-8c15-47fbdd218dc9)



After:

![Image](https://github.com/user-attachments/assets/1bd4ae76-f289-4aef-afd9-c49c31f06947)
