### ISSUE TITLE
🚸 TinaCMS - Improve the reference field selector

### ISSUE THREAD

**Issue by wicksipedia** [tinacms/tinacms#4640]
CC @wicksipedia @tkapa 

Hey Team, 

### Description: 

There are a few issues with the reference type field. 

1. It uses the native os and browser dropdown list components so the experience varies 
2. Only the filename is sent so there isn't much that can be done to filter and work with the reference. 

### Tasks
- [x] Create a dropdown list component that is consistent
- [x] Allow user to search/filter dropdown options
- [x] Update docs

### Screenshots

![Image](https://github.com/user-attachments/assets/9a11e570-3514-46e2-a7d9-5aed6c48cd88)
**Figure: MacOS**

![Image](https://github.com/user-attachments/assets/1e740be7-9c8d-4c61-b714-6e678ea14106)
**Figure: Windows**

**Comment by Ben0189** [comment]
As per my investigation, this will be the closest component that we looking for [combobox](https://ui.shadcn.com/docs/components/combobox)

All reference component stay in reference folder in tinacms 

![Image](https://github.com/user-attachments/assets/8a828214-264f-44b7-993a-06a2ad3910f0)

Following task:
- [ ] Try implement the shadcn combobox into current references field component 
- [ ] Fix popover CSS (some ui rendering issue making the popover content not showing)
- [ ] Migrate code and state from previous select component to new combobox component 
- [ ] Test if combobox working as original select with search functionality 
- [ ] Implement style option for reference field type

**Comment by Ben0189** [comment]
Task left for this PBI 

- [ ] Update Tina io docs for reference field component update 

Notes :
- For current approach title / name field need to be exist in the reference field for the display list to show both title and file name

**Comment by JackDevAU** [comment]
Before:


![Image](https://github.com/user-attachments/assets/879b4b0c-fa15-43c3-bef2-915120876d67)



After:

![Image](https://github.com/user-attachments/assets/9533ef72-2d93-4a17-8507-557c101eb9f3)

**Comment by JackDevAU** [comment]
Hey @HenrySkup 

Yes sorry about that, we have a fix in the newest version. Please update both `tinacms` and `@tinacms/cli` to the latest version
