### ISSUE TITLE
♻️ TinaCMS - Customise the reference field selector

### ISSUE THREAD

**Issue by wicksipedia** [tinacms/tinacms#4707]
CC @wicksipedia @tkapa @Ben0189 

Hey Team, 

### Description: 

Following https://github.com/tinacms/tinacms/pull/4701 we would now like to be able to customise the selector  

### Tasks
- [x] Should be able to style the `option` to include more data than just the filename
  - [x] Extend the `reference` field type and add the following or similar
  - [x] an `options` object that has the following or similar
    - [x] `label: ({field}) => string` - The label to be displayed    
    - [x] `search:string[]` - The field's that should be used to index/search on  
    - [x] `optionOverride` - A custom component that will replace the default option that is rendered. Maybe experiment with replacing the whole List component? 

### Screenshots

![Image](https://github.com/user-attachments/assets/9a11e570-3514-46e2-a7d9-5aed6c48cd88)
**Figure: MacOS**

![Image](https://github.com/user-attachments/assets/1e740be7-9c8d-4c61-b714-6e678ea14106)
**Figure: Windows**

**Comment by Ben0189** [comment]
Progress update 
- [ ] Add display option property to schema tools for reference field 
- [ ] Validate new display option property
- [ ] Refactor graphql query to retrieve display option property
- [ ] Refactor reference field selector component to display content based on option property

**Comment by JackDevAU** [comment]
Before:


![Image](https://github.com/user-attachments/assets/879b4b0c-fa15-43c3-bef2-915120876d67)



After:

![Image](https://github.com/user-attachments/assets/9533ef72-2d93-4a17-8507-557c101eb9f3)

**Comment by ncn-ssw** [comment]
@Ben0189 

Please note that a Done video is required.
- [ ] Done video

**Comment by Ben0189** [comment]
Done video for new reference field - https://www.youtube.com/watch?v=WjxYTxlnZMU

**Comment by Ben0189** [comment]
Documentation pr still under review - https://github.com/tinacms/tina.io/pull/2041

**Comment by Jord-Gui** [comment]
> Documentation pr still under review - [tinacms/tina.io#2041](https://github.com/tinacms/tina.io/pull/2041)

PR has been merged into main
