### ISSUE TITLE
♻️ TinaCMS - Refactor Examples

### ISSUE THREAD

**Issue by JackDevAU** [tinacms/tinacms#4720]
CC @wicksipedia @ncn-ssw @Ben0189 @Jord-Gui 

Hey Team, 

As per my conversation with @ncn-ssw the current examples in the repo aren't great, and some don't work... 

Current Examples - To be removed.

- `examples/basic-iframe`
- `examples/empty`
- `examples/hugo-quickstart`
- `examples/kitchen-sink`
- `examples/next-2024`
- `examples/tina-self-hosted-demo`
- `experimental-examples/kitchen-sink`
- `experimental-examples/tina-cloud-starter`

These will be replaced with the following, 

- next
  - `next/kitchen-sink`
  - `next/self-hosted`
 
- react
  - `react/kitchen-sink`

- astro
  - `astro/kitchen-sink`

- hugo
  - `hugo/kitchen-sink`

This approach will make the examples actually useful, to internal testers as well as the general public to play around and use as reference. 

### Task 
- [ ] Remove old examples
- [ ] Create new kitchen sink examples separated by framework
- [ ] Update docs + Readme

**Comment by 18-th** [comment]
Updated Empty example with the latest supported versions of packages and Tina v3 approaches in #6387 ✅

**Comment by KahaMason** [comment]
Update as of 17/2/26:

PRs: 
* [NextJS - New Kitchen-Sink Example](https://github.com/tinacms/tinacms/pull/6428)

Progress on PR:
- [x] Created new Kitchen Sink app in NextJS 15 & React 18
- [x] Update all the html, components and CSS stylings (many html elements / components / CSS were missing originally)
- [x] Updated to use Biome, ESM, App routing, Server Components + generateStaticParams
- [x] Reformat the content schema for the example content.
- [x] Fix the existing tests in the new next/kitchen-sink example

Remaining work on this Issue:
- [ ] Finalize next/kitchen-sink example
- [ ] Recreate kitchen-sink example in React, Astro & Hugo
- [ ] Remove old examples
- [ ] Update the docs

**Comment by KahaMason** [comment]
👀 [NextJS - New Kitchen-Sink Example](https://github.com/tinacms/tinacms/pull/6428) is ready for review
- New Kitchen-Sink example (NextJS)

**Comment by kulesy** [comment]
✅ Done
