### ISSUE TITLE
📝New Field - Autofilling for meta descriptions 🧠

### ISSUE THREAD

**Issue by Calinator444** [tinacms/tinacms#4792]
CC: @adamcogan, @wicksipedia, @bradystroud

Referenced in https://youtu.be/BvcoRM8NfQ4

### Description

Auto filling SEO information for new pages can be tedious. For better UX we could add a new field for meta descriptions which auto populates itself based on the content of the page. This could be achieved using a webhook which passes the form state to an LLM or OLM either before the user saves or during the save process.

**Notes**
- [ ] I would recommend giving users a choice whether to opt in or create meta description tags manually
- [ ] The user should be able to preview/regenerate the meta description before saving it in markdown
- [ ] Security in this feature is paramount. Look into different routing options for users with data sovereignty concerns. 

### Todo
- [ ] Figure out the best Language model to use for implementing this
- [ ] Have a UX designer create the flow for the auto filling field
- [ ] Create a service level method to connect to the selected LLM through a webhook/api
- [ ] Create the new field type

**Comment by wicksipedia** [comment]
Idea is ok, but this needs to be scoped out by the team
