### ISSUE TITLE
TinaCMS - Build all templates action fails due to PNPM issue + not reporting issues correctly

### ISSUE THREAD

**Issue by brookjeynes-ssw** [tinacms/tinacms#4835]
The build all templates action is currently failing due to an issue with PNPM not installing node modules correctly. GitHub issues are also not being created due to a type in the action.

## Tasks
- [x] Fix the install issue with PNPM
- [x] Fix the typo in the GitHub issue creation command
- [x] Fix the projects to build with local
- [x] Document supported package managers

**Comment by brookjeynes-ssw** [comment]
Done - Supported package managers are now documented and the action successfully creates issues
