### ISSUE TITLE
👀 Spike - TinaCMS | media - serve images that live next to content

### ISSUE THREAD

**Issue by wicksipedia** [tinacms/tinacms#5172]
Based off
```
From: Tylah Kapa [SSW] <TylahKapa@ssw.com.au>
Date: Tuesday, 8 October 2024 at 6:57 PM
To: Matt Wicks [SSW] <MattWicks@ssw.com.au>
Cc: Brady Stroud [SSW] <BradyStroud@ssw.com.au>, Adam Cogan [SSW] <AdamCogan@ssw.com.au>, Jean Thirion [SSW] <JeanThirion@ssw.fr>, Caleb Williams [SSW] <CalebWilliams@ssw.com.au>, Isaac Lombard [SSW] <IsaacLombard@ssw.com.au>, Baba Kamyljanov [SSW] <BabaKamyljanov@ssw.com.au>, Gilles Pothieu [SSW] <GillesPothieu@ssw.fr>, Hugo Pernet [SSW] <HugoPernet@ssw.fr>
Subject: TinaCMS | Can we use relative images?
```

[SSW.Rules](https://github.com/sswconsulting/ssw.rules) want to migrate to TinaCMS

They store images next to content + in a [content repo](https://github.com/sswconsulting/ssw.rules.content), instead of in a `public` directory

The markdown then uses relative paths to the image - that live in the same directory as the content e.g. https://github.com/SSWConsulting/SSW.Rules.Content/tree/main/rules/3-steps-to-a-pbi

![Example of the structure of a rule, with images](https://github.com/user-attachments/assets/ed1e9442-514c-42c1-9938-5bdb5aef1715)
**Figure: Example of the structure of a rule, with images**

![Example of the markdown of a rule, with a relative path to the image](https://github.com/user-attachments/assets/f1b48279-2b32-429b-a8ec-7a0cdccd02c4)
**Figure: Example of the markdown of a rule, with a relative path to the image**

This spike aims to see if we can add config options to TinaCMS to avoid them modifying their content repo

### Tasks
- [ ] Can we do this with no mods to TinaCMS config e.g. point the media config to the content dir
- [ ] Spike - try other methods
- [ ] Draft PBIs for how we should do it

### Acceptance Criteria
  - [ ] Identify the if we can do this without modifying TinaCMS config
  - [ ]  Document findings, including any technical or architectural considerations.
  - [ ]  Propose next steps or a proof of concept based on the research.

**Comment by Ben0189** [comment]
**Finding** 
Business logic for file path constructing at function persist_local in file packages/tinacms/src/toolkit/core/media-store.default.ts

**Possible solution**
Implement a new path constructing logic specifically for rules usage

**Comment by Ben0189** [comment]
As per conversation with @kldavis4 , requirement will be more likely depending on the framework SSW rules using if it support rendering images along side the content

**Comment by Ben0189** [comment]
> Identify the if we can do this without modifying TinaCMS config

We need to modifying the config by adding a new field to the media config (e.g. usingRelativePath : boolean)

> Document findings, including any technical or architectural considerations.

![Image](https://github.com/user-attachments/assets/e4cb6da3-018f-4963-a2ba-0cbb7ba69b41)


> Propose next steps or a proof of concept based on the research.

Need more feedback from Jeff / Kelly

**Comment by Ben0189** [comment]
As per discussion with Jeff, we can potentially split this into few different part.

[Recording](https://sswcom-my.sharepoint.com/personal/jackpettit_ssw_com_au/_layouts/15/stream.aspx?id=%2Fpersonal%2Fjackpettit%5Fssw%5Fcom%5Fau%2FDocuments%2FRecordings%2FSSW%20%2D%20Tina%2D20241114%5F103425%2DMeeting%20Recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E4362069a%2D3c8d%2D437f%2D8730%2Da75e216c1320) with Jeff

- [ ] Finding images and sourcing them into S3 on Tina Cloud
- [ ] Graphql ability to resolve images path
- [ ] How to handle images rendering in dev server
- [ ] Media UI

**Comment by wicksipedia** [comment]
✅ - Done

Video walkthrough - https://sswcom-my.sharepoint.com/:v:/g/personal/matthewwicks_ssw_com_au1/EcbBBt4Ye_BFk9T3LYLVe-oBZJZdyVKw3ZGnfcsHuyx2jg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3d&e=jFhR68&xsdata=MDV8MDJ8TWF0dFdpY2tzQHNzdy5jb20uYXV8NTBlYjY5YjZiYTk5NDU1ZDFjYzkwOGRkYWQ4MWI1ODF8YWMyZjdjMzRiOTM1NDhlOWFiZGMxMWU1ZDRmY2IyYjB8MHwwfDYzODg1NzQ5NDc5OTI2MjU2MHxVbmtub3dufFRXRnBiR1pzYjNkOGV5SkZiWEIwZVUxaGNHa2lPblJ5ZFdVc0lsWWlPaUl3TGpBdU1EQXdNQ0lzSWxBaU9pSlhhVzR6TWlJc0lrRk9Jam9pVFdGcGJDSXNJbGRVSWpveWZRPT18MHx8fA%3d%3d&sdata=dkJZRUFPbW4vZkFkdDBYb0RNOTVPZWYwRWtWbzhWZXozaVV6UnBDZlZwQT0%3d

Repo with demo - https://github.com/wicksipedia/Tina-images-and-content-together

**Comment by Calinator444** [comment]
@wicksipedia, @Ben0189 Were there any PBIs created as a result of this spike?

**Comment by wicksipedia** [comment]
No PBIs created, we settled to documentation for now https://tina.io/docs/guides/storing-media-with-content

**Comment by Freego1783** [comment]
Hey guys,

Adding link to the rule about this topic that contains a video showing 3 options to gorup content and media together: https://www.ssw.com.au/rules/self-contained-images-and-content/
