### ISSUE TITLE
🐛  Lists – Bin Icon – Path 'd' attribute issues on Safari and Tablet

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tinacms#5261]
### Pain

When testing Tina with Adam, the delete button wasn't visible in lists.
Looks to be a browser specific problem.

The button is still clickable, but with no icon it's hard to interpret.

### Initial Investigation

I've replicated the issue on Safari, and if I remember correctly, Adam was using Firefox on an iPad when he encountered the issue.

Using dev tools, it looks like the `d` attribute of the `Path` element isn't getting picked up. 
I couldn't get it to show up either, after 10 minutes of fiddling with the styling.

![Image](https://github.com/user-attachments/assets/efa7e184-4491-4ac3-af40-b96ca63a46d5)
**Figure 1 – icon is visible on Arc (chrome based), you can see the `d` attribute in picked up CSS**

![Image](https://github.com/user-attachments/assets/34f50b91-4094-479e-a4d4-d9d5abbb70fd)
**Figure 2 – icon is not picked up correctly on Safari, you can see the `d` attribute in picked up CSS**

### Tasks

- [ ] Investigate and fix.

Cheers :)

### Reproduction

https://github.com/tinacms/tina.io

### Steps to reproduce

1. Use the CMS with Visual Editing on Safari

### System Info

  System:
    OS: macOS 15.0
    CPU: (12) arm64 Apple M3 Pro
    Memory: 6.26 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.17.0/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 9.12.0 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
  Browsers:
    Edge: 130.0.2849.68
    Safari: 18.0

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by joshbermanssw** [comment]
The delete button in the list view (packages/tinacms/src/admin/pages/CollectionListPage.tsx:1116) now uses <BiTrash> from react-icons/bi:

  Icon: (
    <BiTrash size='1.3rem' className='text-red-500' />
  ),

  react-icons renders inline <svg><path d="..." /></svg> with d as a real XML attribute on the <path> element — which Safari/iPad render reliably. That's the opposite of the pattern that caused
   the original bug (CSS-based d: path(...) rules, which Safari ignores).

<img width="848" height="1078" alt="Image" src="https://github.com/user-attachments/assets/3ecbc669-5fe2-4497-9fae-5b2a0cc318aa" />


**Figure: LGTM**
